### ISSUE TITLE
请问要怎么使用？

### ISSUE THREAD

**Issue by KID-joker** [wen-haoming/visual-dev#1]
要怎么样才是像preview那样，鼠标移上去显示元素区域，点击可以跳转vscode？
1、vue项目
2、webpack已经引入plugin了

**Comment by wen-haoming** [comment]
> 要怎么样才是像preview那样，鼠标移上去显示元素区域，点击可以跳转vscode？ 1、vue项目 2、webpack已经引入plugin了

在屏幕的左下角会有一个小图标，点击即可~

**Comment by KID-joker** [comment]
> > 要怎么样才是像preview那样，鼠标移上去显示元素区域，点击可以跳转vscode？ 1、vue项目 2、webpack已经引入plugin了
> 
> 在屏幕的左下角会有一个小图标，点击即可~

ok，找到了。preview里的动作太小了，没注意到。
感谢您的开源！

**Comment by wen-haoming** [comment]
> 
谢谢支持~
